name: Android Release

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore and Set Environment Variables
        env:
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo $SIGNING_KEY_BASE64 | base64 --decode > $GITHUB_WORKSPACE/release.jks
          echo "SIGNING_KEY_FILE=$GITHUB_WORKSPACE/release.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" >> $GITHUB_ENV
          echo "KEY_ALIAS=$KEY_ALIAS" >> $GITHUB_ENV
          echo "KEY_PASSWORD=$KEY_PASSWORD" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Rename APK for Release
        id: rename_apk
        run: |
          SOURCE_APK=$(find app/build/outputs/apk/release -type f -name "*.apk" | head -n 1)
          TAG_NAME=${{ github.event.release.tag_name }}

          NEW_NAME="Calculator-${TAG_NAME}.apk"
          NEW_PATH="app/build/outputs/apk/release/${NEW_NAME}"

          mv $SOURCE_APK $NEW_PATH

          echo "apk_path=$NEW_PATH" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.rename_apk.outputs.apk_path }}